stages:
  - test
  - history_copy
  - generate_report
  - report

test-job:
  stage: test
  artifacts:
    when: always
    paths:
      - allure_results
    expire_in: 1 day
  script:
    pytest - v tests/test_integra_partner_basic.py --alluredir allure_results
  allow_failure: true

hist-job:
  stage: history_copy
  artifacts:
    when: always
    paths:
      - allure reports
    expire_in: 1 day
  script:
    - 'curl --location --output artifacts.zip "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/jobs/artifacts/main/download?job=pages&job_token=$CI_JOB_TOKEN"'
    - unzip artifacts.zip
    - chmod -R 777 public
    - cp ./public/history/* ./allure_results
  allow_failure: true

report-job:
  stage: generate_report
  script:
    - allure generate -c allure_results -o allure-report
  artifacts:
    paths:
      - ./allure-results
      - ./allure-report
    expire_in: 1 day
  rules:
    - when: always

pages:
  stage: report
  script:
    - mkdir public
    - cp -r ./allure-report/* public
  artifacts:
    paths:
      - public
    expire_in: never
  needs:
    - job: generate_report