stages:
  - test
  - history_copy
  - generate_report
  - report

test-job:
  stage: test
  artifacts:
    when: always
    paths:
      - allure_results
    expire_in: 1 day
  script:
    pytest -v tests/test_integra_partner_basic.py --alluredir allure_results
  allow_failure: true

history_copy:
    stage: history_copy
    artifacts:
        when: always
        paths:
            - allure_results
        expire_in: 1 day
    script:
        - Remove-item alias:curl
        - 'curl --location --output artifacts.zip --header "PRIVATE-TOKEN: glpat-xGzQFG2d2yt4xy8qg1FX" "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/jobs/artifacts/main/download?job=job_name"'
        - Expand-Archive artifacts.zip
        - chmod -R 777 public
        - Copy-Item -r ./public/history/* ./allure_results
    allow_failure: true

report-job:
  stage: generate_report
  script:
    - allure generate -c allure_results
  artifacts:
    paths:
      - ./allure_results
      - ./allure-report
    expire_in: 1 day
  rules:
    - when: always

pages:
  stage: report
  script:
    - mkdir public
    - Copy-Item -r ./allure-report/* public
  artifacts:
    paths:
      - public
    expire_in: never
  needs:
    - job: report-job