stages:
  - test
  - history_copy
  - generate_report
  - pages

test-job:
  stage: test
  script:
    pytest -v tests/test_integra_partner_basic.py --alluredir allure_results
    mkdir ./allure_results/history
  allow_failure: true
  artifacts:
    when: always
    paths:
      - allure_results
    expire_in: 1 day

history_copy:
    stage: history_copy
    script:
        - Remove-item alias:curl
        - 'curl --location --output artifacts.zip --header "PRIVATE-TOKEN: glpat-xGzQFG2d2yt4xy8qg1FX" "https://gitlab.com/api/v4/projects/41729950/jobs/artifacts/main/download?job=pages"'
        - Expand-Archive artifacts.zip
        - Copy-Item -Path ./artifacts/public/history/* -Destination ./allure_results/history
    allow_failure: true
    artifacts:
      when: always
      paths:
        - allure_results
      expire_in: 1 day
    rules:
      - when: always

report-job:
  stage: generate_report
  script:
    - allure generate -c allure_results -o allure_report
  artifacts:
    paths:
      - ./allure_results
      - ./allure_report
    expire_in: 1 day
  rules:
    - when: always

pages:
  stage: pages
  script:
    - mkdir public
    - Move-Item -Path ./allure_report/* -Destination public
  artifacts:
    paths:
      - public
    expire_in: never