stages:
  - test
  - history_copy
  - generate_report
  - report

test-job:
  stage: test
  artifacts:
    when: always
    paths:
      - allure_results
    expire_in: 1 day
  script:
    pytest -v tests/test_integra_partner_basic.py --alluredir allure_results
  allow_failure: true

report-job:
  stage: generate_report
  script:
    - allure generate -c allure_results -o allure_report
  artifacts:
    paths:
      - ./allure_results
      - ./allure_report
    expire_in: 1 day
  rules:
    - when: always

pages:
  stage: report
  script:
    - mkdir public
    - cp -r ./allure_report/* public
  artifacts:
    paths:
      - public
    expire_in: never
  needs:
    - job: report-job